### PR TITLE
Fixed error in options parsing

### PR DESCRIPTION
**Pull request by KSDaemon**
Hi! There is one mistake in parsing options. I fixed!

### CODE REVIEW

**Comment by KSDaemon** [comment]
Will be great, if you can publish a new release!

**Comment by DevNebulae** [comment]
I can confirm that this fix works with webpack version 2.1.1. Would love to see this in the main branch.

**Comment by KSDaemon** [comment]
Great! Two good things done is better than one :)

**Comment by at0g** [comment]
@KSDaemon 
To preserve backwards compatibility, the changes from PR #48 (that this PR depends on) have been reverted and the update released as `v2.4.8`. 
Please feel free to update and reopen this PR if you like.

**Comment by KSDaemon** [comment]
Well... As of:
```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
I don't see any reason, why not to switch to getOptions().
Sorry, if i don't correctly understand, what you mean under backwards compatibility... If you mean supporting both webpack 1.x and 2.x versions... Current version works great with webpack 1.x, and development of webpack 1.x itself was stopped. I think we can switch to 2.x. Your opinions?

**Comment by at0g** [comment]
regarding the backwards compatibility: `loader-utils@1.x`requires a newer version of node, so has the potential to break existing installs (see #50) - making the switch to getOptions a major version bump for this project.
To avoid breaking (anymore) existing installs using 3.x of this project, I've reverted the latest updates and released that as the latest patch on 3.x.

**Comment by KSDaemon** [comment]
Now i see! Agree. Thnx!

**Pull request closed without merging**
